const app=document.querySelector('#app');let state={token:localStorage.token,user:null,folder:'inbox',emails:[],selected:null,config:{emailDomain:'demo.phonemail.test',demoOtp:true,externalEmailEnabled:false}};
const api=async(path,opt={})=>{const headers={authorization:'Bearer '+state.token,...opt.headers};if(!(opt.body instanceof FormData))headers['content-type']='application/json';let r=await fetch('/api'+path,{...opt,headers});let d=await r.json();if(!r.ok)throw Error(d.error);return d};
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function auth(register=false){
  let verified=false;
  app.innerHTML=`<section class="auth"><div class="card"><div class="brand">✦ PhoneMail</div><h1>${register?'Create your PhoneMail':'Welcome back'}</h1><p class="muted">${register?'Verify your phone to create a demo account.':'Log in with your phone number and password.'}</p><form id="authform"><label class="field">Phone number<input name="phone" type="tel" autocomplete="tel" placeholder="+919876543210" required></label>${register?'<label class="field">Display name<input name="name" placeholder="Your name" required></label>':''}<label class="field">Password<input name="password" type="password" minlength="${register?'8':'1'}" autocomplete="${register?'new-password':'current-password'}" required></label>${register?'<button class="ghost" id="request-otp" type="button">Send verification code</button><label class="field">Six-digit code<input name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" placeholder="123456" required></label><button class="ghost" id="verify-otp" type="button">Verify code</button>':''}<p class="muted" id="authinfo">${register&&state.config.demoOtp?'Demo mode: no SMS is sent; the code will be shown here.':''}</p><p class="notice" id="error" role="alert"></p><button class="primary" id="auth-submit" ${register?'disabled':''}>${register?'Create account':'Log in'}</button></form><p class="muted">${register?'Already registered?':'New here?'} <button class="link" id="switch">${register?'Log in':'Create an account'}</button></p></div></section>`;
  document.querySelector('#switch').onclick=()=>auth(!register);
  const form=document.querySelector('#authform'),errorMessage=document.querySelector('#error'),info=document.querySelector('#authinfo');
  const phone=()=>String(new FormData(form).get('phone')||'').trim();
  if(register){
    document.querySelector('#request-otp').onclick=async e=>{e.currentTarget.disabled=true;errorMessage.textContent='';try{const d=await api('/auth/otp/request',{method:'POST',body:JSON.stringify({phone:phone()})});info.textContent=d.demoCode?`Demo only: no SMS was sent. Enter this code: ${d.demoCode}`:d.message;document.querySelector('[name="code"]').focus()}catch(x){errorMessage.textContent=x.message}finally{e.currentTarget.disabled=false}};
    document.querySelector('#verify-otp').onclick=async e=>{e.currentTarget.disabled=true;errorMessage.textContent='';try{await api('/auth/otp/verify',{method:'POST',body:JSON.stringify({phone:phone(),code:new FormData(form).get('code')})});verified=true;info.textContent='Phone number verified for this demo account.';document.querySelector('#auth-submit').disabled=false}catch(x){errorMessage.textContent=x.message}finally{e.currentTarget.disabled=false}};
  }
  form.onsubmit=async e=>{e.preventDefault();const button=document.querySelector('#auth-submit');button.disabled=true;errorMessage.textContent='';try{const data=Object.fromEntries(new FormData(form));let d=await api('/auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify(data)});state.token=d.token;state.user=d.user;localStorage.token=d.token;await load()}catch(x){errorMessage.textContent=x.message||'Could not connect to PhoneMail. Check that the server and database are running.';button.disabled=register?!verified:false}};
}
async function load(){try{let d=await api('/emails?folder='+state.folder);state.emails=d.emails;render()}catch(e){const expired=e.message==='Please log in.';if(expired){localStorage.removeItem('token');state.token=null;state.user=null;auth();return}app.innerHTML=`<section class="auth"><div class="card"><div class="brand">✦ PhoneMail</div><h1>Mailbox unavailable</h1><p class="notice" role="alert">${esc(e.message||'Could not load your mailbox.')}</p><button class="primary" id="retry">Retry</button><button class="link" id="logout-auth">Log out</button></div></section>`;document.querySelector('#retry').onclick=load;document.querySelector('#logout-auth').onclick=()=>{localStorage.removeItem('token');state.token=null;state.user=null;auth()}}}
function nav(){return ['inbox','sent','drafts','spam','favorites','trash'].map(x=>`<button class="nav ${state.folder===x?'active':''}" data-folder="${x}">${x==='inbox'?'Inbox':x==='favorites'?'★ Favorites':x[0].toUpperCase()+x.slice(1)}</button>`).join('')}
function render(){
  let selected=state.selected&&state.emails.find(e=>e.id===state.selected.id)||state.selected;
  app.innerHTML=`<section class="shell">
    <header class="topbar"><button class="mobile-menu" aria-label="Open menu">☰</button><div class="topbrand"><span>✦</span> PhoneMail</div><div class="account-chip" title="${esc(state.user?.email||'')}">${esc((state.user?.name||state.user?.email||'P').slice(0,1).toUpperCase())}</div></header>
    <div class="address-note"><span class="note-icon">i</span><span>Demo PhoneMail IDs work inside this app, for example <strong>9876543210@${esc(state.config.emailDomain)}</strong>. External email ${state.config.externalEmailEnabled?'is enabled through the verified sender.':'is disabled until an email sender is configured.'}</span></div>
    <aside class="sidebar"><button class="compose" data-compose><span>＋</span> Compose</button><div class="navgroup">${nav()}</div><div class="profile"><span class="profile-name">${esc(state.user?.name||'')}</span><span>${esc(state.user?.email||'')}</span><button class="link" id="logout">Log out</button></div></aside>
    <section class="list ${selected?'hide':''}"><header class="listhead"><div class="mobiletop"><span class="brand">✦ PhoneMail</span><button class="ghost" id="mobcompose" data-compose aria-label="Compose">＋</button></div><input class="search" id="search" placeholder="Search mail" aria-label="Search mail"></header><div id="maillist">${mails()}</div><button class="compose floating" id="floating" data-compose>＋ Compose</button></section>
    <section class="reader ${selected?'show':''} ${selected?'':'empty'}" id="reader">${selected?reader(selected):'<div class="empty-state"><span>✉</span><p>Select a message to read</p></div>'}</section>
  </section>`;
  document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folder=b.dataset.folder;state.selected=null;load()});
  document.querySelector('#logout').onclick=()=>{localStorage.removeItem('token');state.token=null;auth()};
  document.querySelectorAll('[data-compose]').forEach(button=>button.onclick=()=>compose());
  const mobileCompose=document.querySelector('.mobile-menu');mobileCompose.onclick=()=>compose();mobileCompose.textContent='＋';mobileCompose.setAttribute('aria-label','Compose');
  document.querySelector('#search').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelector('#maillist').innerHTML=mails(q)};
  document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>open(b.dataset.id));
  document.querySelectorAll('[data-attachment]').forEach(b=>b.onclick=()=>downloadAttachment(b.dataset.attachment));
  if(selected){document.querySelector('#back').onclick=()=>{state.selected=null;render()};if(document.querySelector('#reply'))document.querySelector('#reply').onclick=()=>compose(selected);if(document.querySelector('#trash'))document.querySelector('#trash').onclick=()=>act(selected.id,'trash');if(document.querySelector('#spam'))document.querySelector('#spam').onclick=()=>act(selected.id,'spam');if(document.querySelector('#notspam'))document.querySelector('#notspam').onclick=()=>act(selected.id,'inbox');if(document.querySelector('#fav'))document.querySelector('#fav').onclick=()=>act(selected.id,'favorite');if(document.querySelector('#save-draft'))document.querySelector('#save-draft').onclick=()=>compose(null,selected)}
}
function mails(q=''){return state.emails.filter(e=>[e.from,e.to,e.subject,e.body].join(' ').toLowerCase().includes(q)).map(e=>`<button class="mail ${e.read?'':'unread'}" data-id="${e.id}"><strong>${esc(state.folder==='sent'||state.folder==='drafts'?e.to:e.from)} ${e.favorite?'★':''}</strong><span>${esc(e.subject||'(no subject)')} · ${esc(e.body)}</span><span>${new Date(e.createdAt).toLocaleString()}</span></button>`).join('')||'<p class="muted" style="padding:20px">No messages here yet.</p>'}
function reader(e){const isDraft=state.folder==='drafts';const attachments=e.attachments?.length?`<section class="attachments"><h3>Attachments (${e.attachments.length})</h3>${e.attachments.map(a=>`<button class="attachment" data-attachment="${esc(a.id)}"><span>📎</span><span>${esc(a.filename)}<small>${formatSize(a.sizeBytes)}</small></span><span class="download-icon">↓</span></button>`).join('')}</section>`:'';return `<button class="ghost" id="back">← Back</button><h1>${esc(e.subject||'(no subject)')}</h1><p class="meta">From ${esc(e.from)}<br>To ${esc(e.to||'')}</p><article class="body">${esc(e.body)}</article>${attachments}<div class="actions">${isDraft?'<button class="primary" id="save-draft" style="width:auto">Edit draft</button>':state.folder!=='sent'?'<button class="primary" id="reply" style="width:auto">Reply</button>':''}${state.folder==='inbox'?'<button class="ghost" id="spam">Mark as spam</button>':''}${state.folder==='spam'?'<button class="ghost" id="notspam">Not spam</button>':''}${state.folder!=='drafts'&&state.folder!=='trash'?`<button class="ghost" id="fav">${e.favorite?'★ Remove favorite':'☆ Add to favorites'}</button>`:''}${state.folder!=='trash'?`<button class="ghost" id="trash">${isDraft?'Discard draft':'Move to trash'}</button>`:''}</div>`}
function formatSize(size){if(!size)return '';return size<1024?`${size} B`:size<1024*1024?`${(size/1024).toFixed(1)} KB`:`${(size/1024/1024).toFixed(1)} MB`}
async function downloadAttachment(id){try{const r=await fetch('/api/attachments/'+encodeURIComponent(id),{headers:{authorization:'Bearer '+state.token}});if(!r.ok){const d=await r.json();throw Error(d.error||'Could not download attachment.')}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a'),disposition=r.headers.get('content-disposition')||'',match=disposition.match(/filename="?([^";]+)"?/i);a.href=url;a.download=match?decodeURIComponent(match[1]):'attachment';a.click();URL.revokeObjectURL(url)}catch(e){alert(e.message)}}
async function open(id){state.selected=state.emails.find(e=>e.id===id);let d=await api('/emails/'+id);state.selected=d.email;render()}
async function act(id,a){await api('/emails/'+id+'/'+a,{method:'POST'});state.selected=null;load()}
function compose(reply,draft){
  if(document.querySelector('.modal'))return;
  let to=draft?.to||(reply?reply.from.match(/<(.+)>/)?.[1]:'');
  app.insertAdjacentHTML('beforeend',`<div class="modal"><form class="card" id="composeform" enctype="multipart/form-data"><div class="brand">${reply?'Reply':draft?'Edit draft':'New message'}</div><label class="field">To<input name="to" value="${esc(to)}" ${reply?'readonly':''}></label><label class="field">Subject<input name="subject" value="${esc(draft?.subject||(reply?(reply.subject.startsWith('Re:')?reply.subject:'Re: '+reply.subject):''))}"></label><label class="field">Message<textarea name="body" rows="8">${esc(draft?.body||'')}</textarea></label><label class="field attachment-picker">Attachments<input name="attachments" type="file" multiple><small>Up to 5 files, 10 MB each</small></label><p class="notice" id="composeerror"></p><button class="primary" type="submit">${draft?'Save and send':'Send email'}</button><button class="ghost" id="save-only" type="button">Save draft</button><button type="button" class="link" id="cancel">Cancel</button></form></div>`);
  const modal=app.querySelector('.modal'),form=modal.querySelector('#composeform');
  modal.querySelector('#cancel').onclick=()=>modal.remove();
  const submit=async(send)=>{const data=new FormData(form);if(!send&&!draft)data.set('draft','true');try{if(send){if(draft)await api('/emails/'+draft.id+'/send-draft',{method:'POST',body:data});else if(reply)await api('/emails/'+reply.id+'/reply',{method:'POST',body:data});else await api('/emails',{method:'POST',body:data});state.folder='sent'}else if(draft){await api('/emails/'+draft.id+'/draft',{method:'PUT',body:data});state.folder='drafts'}else{await api('/emails',{method:'POST',body:data});state.folder='drafts'}modal.remove();state.selected=null;load()}catch(x){modal.querySelector('#composeerror').textContent=x.message}};
  form.onsubmit=e=>{e.preventDefault();submit(true)};
  modal.querySelector('#save-only').onclick=()=>submit(false);
}
(async()=>{try{state.config=await fetch('/api/config').then(r=>r.json())}catch{}if(!state.token)return auth();try{state.user=(await api('/auth/me')).user;load()}catch{auth()}})();
