const app=document.querySelector('#app');let state={token:localStorage.token,user:null,folder:'inbox',emails:[],selected:null};
const api=async(path,opt={})=>{let r=await fetch('/api'+path,{...opt,headers:{'content-type':'application/json',authorization:'Bearer '+state.token,...opt.headers}});let d=await r.json();if(!r.ok)throw Error(d.error);return d};
const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function auth(register=false){app.innerHTML=`<section class="auth"><div class="card"><div class="brand">✦ PhoneMail</div><h1>${register?'Create your PhoneMail':'Welcome back'}</h1><p class="muted">Your phone number becomes your email identity.</p><form id="authform"><label class="field">Phone number<input name="phone" inputmode="numeric" placeholder="9876543210" required></label>${register?'<label class="field">Display name<input name="name" placeholder="Your name"></label>':''}<label class="field">Password<input name="password" type="password" minlength="4" required></label><p class="notice" id="error"></p><button class="primary">${register?'Create account':'Log in'}</button></form><p class="muted">${register?'Already registered?':'New here?'} <button class="link" id="switch">${register?'Log in':'Create an account'}</button></p></div></section>`;document.querySelector('#switch').onclick=()=>auth(!register);document.querySelector('#authform').onsubmit=async e=>{e.preventDefault();try{let d=await api('/auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});state.token=d.token;state.user=d.user;localStorage.token=d.token;load()}catch(x){error.textContent=x.message}}}
async function load(){try{let d=await api('/emails?folder='+state.folder);state.emails=d.emails;render()}catch{localStorage.removeItem('token');state.token=null;auth()}}
function nav(){return ['inbox','sent','drafts','spam','trash'].map(x=>`<button class="nav ${state.folder===x?'active':''}" data-folder="${x}">${x==='inbox'?'Inbox':x[0].toUpperCase()+x.slice(1)}</button>`).join('')}
function render(){let selected=state.selected&&state.emails.find(e=>e.id===state.selected.id)||state.selected;app.innerHTML=`<section class="shell"><aside class="sidebar"><div class="brand">✦ PhoneMail</div><button class="compose">＋ Compose</button><div>${nav()}</div><div class="profile">${esc(state.user?.name||'')}<br>${esc(state.user?.email||'')}<br><button class="link" id="logout">Log out</button></div></aside><section class="list ${selected?'hide':''}"><header class="listhead"><div style="flex:1"><div class="mobiletop"><span class="brand">✦ PhoneMail</span><button class="ghost" id="mobcompose">＋</button></div><input class="search" id="search" placeholder="Search mail"></div><button class="compose" style="display:none" id="unused"></button></header><div id="maillist">${mails()}</div><button class="compose" id="floating" style="position:fixed;right:20px;bottom:20px;width:auto">＋ Compose</button></section><section class="reader ${selected?'show':''} ${selected?'':'empty'}" id="reader">${selected?reader(selected):'<div>Select an email to read it</div>'}</section></section>`;document.querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folder=b.dataset.folder;state.selected=null;load()});document.querySelector('#logout').onclick=()=>{localStorage.removeItem('token');state.token=null;auth()};document.querySelector('#floating').onclick=compose;document.querySelector('#mobcompose').onclick=compose;document.querySelector('#search').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelector('#maillist').innerHTML=mails(q)};document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>open(b.dataset.id));if(selected){document.querySelector('#back').onclick=()=>{state.selected=null;render()};document.querySelector('#reply').onclick=()=>compose(selected);document.querySelector('#trash').onclick=()=>act(selected.id,'trash');document.querySelector('#fav').onclick=()=>act(selected.id,'favorite')}}
function mails(q=''){return state.emails.filter(e=>[e.from,e.subject,e.body].join(' ').toLowerCase().includes(q)).map(e=>`<button class="mail ${e.read?'':'unread'}" data-id="${e.id}"><strong>${esc(state.folder==='sent'?e.to:e.from)}</strong><span>${esc(e.subject)} · ${esc(e.body)}</span><span>${new Date(e.createdAt).toLocaleString()}</span></button>`).join('')||'<p class="muted" style="padding:20px">No messages here yet.</p>'}
function reader(e){return `<button class="ghost" id="back">← Back</button><h1>${esc(e.subject)}</h1><p class="meta">From ${esc(e.from)}<br>To ${esc(e.to)} · ${new Date(e.createdAt).toLocaleString()}</p><article class="body">${esc(e.body)}</article><div class="actions"><button class="primary" id="reply" style="width:auto">Reply</button>${state.folder!=='sent'?`<button class="ghost" id="trash">Move to trash</button><button class="ghost" id="fav">${e.favorite?'★ Favorited':'☆ Favorite'}</button>`:''}</div>`}
async function open(id){state.selected=state.emails.find(e=>e.id===id);let d=await api('/emails/'+id);state.selected=d.email;render()}
async function act(id,a){await api('/emails/'+id+'/'+a,{method:'POST'});state.selected=null;load()}
function compose(reply){let to=reply?reply.from.match(/<(.+)>/)?.[1]:'';app.insertAdjacentHTML('beforeend',`<div class="modal"><form class="card" id="composeform"><div class="brand">${reply?'Reply':'New message'}</div><label class="field">To<input name="to" value="${esc(to)}" required ${reply?'readonly':''}></label><label class="field">Subject<input name="subject" value="${esc(reply?(reply.subject.startsWith('Re:')?reply.subject:'Re: '+reply.subject):'')}" required></label><label class="field">Message<textarea name="body" rows="8" required></textarea></label><p class="notice" id="composeerror"></p><button class="primary">Send email</button><button type="button" class="link" id="cancel">Cancel</button></form></div>`);cancel.onclick=()=>document.querySelector('.modal').remove();composeform.onsubmit=async e=>{e.preventDefault();try{let f=Object.fromEntries(new FormData(e.target));if(reply)await api('/emails/'+reply.id+'/reply',{method:'POST',body:JSON.stringify(f)});else await api('/emails',{method:'POST',body:JSON.stringify(f)});document.querySelector('.modal').remove();state.folder='sent';state.selected=null;load()}catch(x){composeerror.textContent=x.message}}}
(async()=>{if(!state.token)return auth();try{state.user=(await api('/auth/me')).user;load()}catch{auth()}})();
